---
kind: Secret
apiVersion: v1
metadata:
  name: jenkins-secrets
type: Opaque
data:
  # All values for secrets should be provided in base64 encoding
  SECRET_JENKINS_ADMIN_ADDRESS: YWRtaW5AZXhhbXBsZS5jb20=
  SECRET_JENKINS_URL: aHR0cDovL2plbmtpbnMubmF0aGFuZHJldy5vcmcK
  SECRET_JENKINS_PASSWORD: dGhpcy1pcy1hLXBhc3N3b3JkLXNvLXRoZXJlCg==
